# SmartCache Configuration File
# Generated on 2025-08-13

# Default network for contract operations
# Options: arbitrum-sepolia, arbitrum-one, arbitrum-nova, localhost
network = "arbitrum-sepolia"

# Your wallet address that deployed the contracts, this is required for all operations
deployed_by = "0x9f370C970f95F7aEf09E14E061CB74f0657EAD8E"

# Optional: Default contract address
# If specified, you can run 'smart-cache add' without providing an address
contract_address = "0xa92156fd3a8573b5c4fe4bdce567ddf5a2f5e864"

# Optional: Default contract metadata
# name = "MyContract"
# description = "Contract description"
version = "1.0.0"

# CLI behavior settings
interactive = false

# Optional: Custom metadata (add any additional fields you need)
# [metadata]
# author = "Your Name"
# license = "MIT"
# tags = ["defi", "nft"]
